const { execSync } = require('child_process');
const fs = require('fs-extra');
const path = require('path');

async function setupGit(targetDir) {
  // Check if already a git repo
  if (await fs.pathExists(path.join(targetDir, '.git'))) {
    return { initialized: false, message: 'Already a git repository' };
  }
  
  // Initialize repo
  execSync('git init', { cwd: targetDir, stdio: 'ignore' });
  
  // Create .gitignore
  const gitignore = `# Janebot Context Environment - Gitignore
# Generated by janebot-cli

# Secrets
.env
*.env
secrets.*

# Node modules
node_modules/

# Cache
.cache/
*.cache

# OS files
.DS_Store
Thumbs.db

# Editor files
*.swp
*.swo
*~
.vscode/
.idea/

# QMD index (can be regenerated)
.qmd/
`;
  
  await fs.writeFile(path.join(targetDir, '.gitignore'), gitignore);
  
  // Create initial commit
  execSync('git add -A', { cwd: targetDir, stdio: 'ignore' });
  execSync('git commit -m "init: Context environment bootstrap via janebot-cli"', { 
    cwd: targetDir, 
    stdio: 'ignore' 
  });
  
  return { initialized: true };
}

module.exports = { setupGit };
