const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');
const inquirer = require('inquirer');

/**
 * Prompt user for OpenClaw configuration
 * Collects LLM provider, API key, and Telegram bot token
 */
async function promptOpenClawConfig() {
  console.log(chalk.bold.blue('\n🔧 OpenClaw Configuration\n'));
  console.log(chalk.gray('OpenClaw powers the trading agent\'s decision-making and communication.\n'));

  const answers = await inquirer.prompt([
    {
      type: 'list',
      name: 'llmProvider',
      message: 'LLM Provider:',
      choices: [
        { name: 'OpenAI (GPT-4o)', value: 'openai' },
        { name: 'Anthropic (Claude)', value: 'anthropic' },
        { name: 'Venice AI', value: 'venice' },
        { name: 'Local (LM Studio)', value: 'local' }
      ],
      default: 'openai'
    },
    {
      type: 'input',
      name: 'llmApiKey',
      message: 'LLM API Key:',
      when: (answers) => answers.llmProvider !== 'local',
      validate: (input) => input.length > 0 || 'API key is required'
    },
    {
      type: 'list',
      name: 'llmModel',
      message: 'Model:',
      choices: (answers) => {
        switch (answers.llmProvider) {
          case 'openai':
            return ['gpt-4o', 'gpt-4o-mini', 'o1-mini'];
          case 'anthropic':
            return ['claude-3-5-sonnet', 'claude-3-5-haiku'];
          case 'venice':
            return ['llama-3.3-70b', 'qwen-2.5-72b'];
          default:
            return ['local'];
        }
      },
      default: (answers) => {
        switch (answers.llmProvider) {
          case 'openai': return 'gpt-4o';
          case 'anthropic': return 'claude-3-5-sonnet';
          default: return 'local';
        }
      }
    },
    {
      type: 'confirm',
      name: 'enableTelegram',
      message: 'Enable Telegram bot? (recommended for bot communication)',
      default: true
    },
    {
      type: 'input',
      name: 'telegramBotToken',
      message: 'Telegram Bot Token (from @BotFather):',
      when: (answers) => answers.enableTelegram,
      validate: (input) => {
        if (!input) return 'Bot token is required to enable Telegram';
        if (!input.match(/^\d+:[A-Za-z0-9_-]+$/)) return 'Invalid bot token format';
        return true;
      }
    },
    {
      type: 'confirm',
      name: 'enableDiscord',
      message: 'Enable Discord bot? (optional)',
      default: false
    },
    {
      type: 'input',
      name: 'discordBotToken',
      message: 'Discord Bot Token:',
      when: (answers) => answers.enableDiscord
    }
  ]);

  return {
    llm: {
      provider: answers.llmProvider,
      model: answers.llmModel,
      apiKey: answers.llmApiKey || ''
    },
    channels: {
      telegram: {
        enabled: answers.enableTelegram,
        botToken: answers.telegramBotToken || ''
      },
      discord: {
        enabled: answers.enableDiscord,
        botToken: answers.discordBotToken || ''
      }
    }
  };
}

/**
 * Render OpenClaw config from template
 */
function renderOpenClawConfig(config) {
  return {
    version: 1,
    bot_id: config.botId || '',
    agent: {
      name: config.agentName || 'Jane',
      persona: config.persona || 'direct'
    },
    models: {
      default: {
        provider: config.llm.provider,
        model: config.llm.model,
        api_key: config.llm.apiKey
      }
    },
    channels: {
      telegram: {
        enabled: config.channels.telegram.enabled,
        bot_token: config.channels.telegram.botToken,
        allowed_chats: []
      },
      discord: {
        enabled: config.channels.discord.enabled,
        bot_token: config.channels.discord.botToken,
        guild_id: '',
        channels: {}
      }
    },
    workspace: {
      dir: config.workspaceDir || '/opt/trading-agent/workspace'
    }
  };
}

/**
 * Write OpenClaw config to disk
 */
async function writeOpenClawConfig(targetDir, config) {
  const openclawDir = path.join(targetDir, '.openclaw');
  await fs.ensureDir(openclawDir);

  const configPath = path.join(openclawDir, 'config.json');
  await fs.writeJson(configPath, config, { spaces: 2 });

  // Also write a .env file for sensitive values
  const envPath = path.join(openclawDir, '.env');
  const envContent = `# OpenClaw Environment - Generated by downrigger
# Source this file before starting OpenClaw

# LLM Configuration
OPENCLAW_LLM_PROVIDER="${config.models.default.provider}"
OPENCLAW_LLM_MODEL="${config.models.default.model}"
OPENCLAW_LLM_API_KEY="${config.models.default.api_key}"

# Telegram Bot
TELEGRAM_BOT_TOKEN="${config.channels.telegram.bot_token}"

# Discord Bot (optional)
DISCORD_BOT_TOKEN="${config.channels.discord.bot_token}"
`;
  await fs.writeFile(envPath, envContent);

  // Secure the files
  await fs.chmod(configPath, 0o600);
  await fs.chmod(envPath, 0o600);

  return { configPath, envPath };
}

module.exports = {
  promptOpenClawConfig,
  renderOpenClawConfig,
  writeOpenClawConfig
};
